# Generated by Django 5.2.1 on 2025-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='menor',
            field=models.BooleanField(default=False),
        ),
    ]
